app: # 应用基本配置
  env: local # 环境名称
  port: 8080 # 服务监听端口号
  app_name: file-upload # 应用名称
  app_url: http://localhost # 应用域名
minio: # MinIO配置
  access_key: "6CZ8NJV0HZIOIDAYL9Z2"
  secret_key: "cXu+Oigt5h+sjgVZNIyV+BznCgv1GUYENwxsCYLH"
  end_point: "101.33.208.122"
  port: "9000"
  bucket_name: "file-upload"

#database:
#  driver: mysql # 数据库驱动
#  host: 101.33.208.122 # 域名
#  port: 3306 # 端口号
#  database: go_test # 数据库名称
#  username: root # 用户名
#  password: 010603@liu # 密码
#  charset: utf8 # 编码格式
#  max_idle_conns: 10 # 空闲连接池中连接的最大数量
#  max_open_conns: 100 # 打开数据库连接的最大数量
#  log_mode: info # 日志级别
#  enable_file_log_writer: true # 是否启用日志文件
#  log_filename: sql.log # 日志文件名称
#
